OpenMP/Fortran: extend 'adjust_args' clause, fixes for it and declare variant [PR115271]: avoid 'error: variable ‘saved_loc2’ set but not used [-Werror=unused-but-set-variable]'
    [...]/source-gcc/gcc/fortran/openmp.cc: In function ‘match gfc_match_omp_declare_variant()’:
    [...]/source-gcc/gcc/fortran/openmp.cc:7127:25: error: variable ‘saved_loc2’ set but not used [-Werror=unused-but-set-variable]
     7127 |                   locus saved_loc2 = gfc_current_locus;
          |                         ^~~~~~~~~~

Fix-up for OG14 commit e0246616020e95e74afa9d504c8848e6e905fab4
"OpenMP/Fortran: extend 'adjust_args' clause, fixes for it and declare variant [PR115271]".

	PR fortran/115271
	gcc/fortran/
	* openmp.cc (gfc_match_omp_declare_variant): Remove
	'locus saved_loc2'.