re PR tree-optimization/36879 (undefined reference to a variable)
2008-07-20  Andrew Pinski  <andrew_pinski@playstation.sony.com>

        PR tree-opt/36879
        * tree-switch-conversion.c (build_one_array): Call
        varpool_mark_needed_node and varpool_finalize_decl
        instead of assemble_variable.

2008-07-20  Andrew Pinski  <andrew_pinski@playstation.sony.com>

        PR tree-opt/36879
        * gcc.c-torture/execute/20080719-1.c: New testcase.

From-SVN: r138012