Fix tree.cc compilation on SPARC
commit 4d7baa94a48c27030c8ffcfaf3dd187be09903a9
Author: Andrew Pinski <quic_apinski@quicinc.com>
Date:   Sun Jul 13 11:56:03 2025 -0700

    tree: Add include to tm_p.h to tree.cc [PR120866]

broke SPARC bootstrap:

In file included from ./tm_p.h:4,
                 from /vol/gcc/src/hg/master/local/gcc/tree.cc:35:
/vol/gcc/src/hg/master/local/gcc/config/sparc/sparc-protos.h:46:47: error: use of enum ‘memmodel’ without previous declaration
   46 | extern void sparc_emit_membar_for_model (enum memmodel, int, int);
      |

Fixed by including memmodel.h.

Bootstrapped without regressions on sparc-sun-solaris2.11 and
i386-pc-solaris2.11.

2025-07-15  Rainer Orth  <ro@CeBiTec.Uni-Bielefeld.DE>

	gcc:
	* tree.cc: Include memmodel.h.