RISC-V: testsuite: Fix broken testsuite error of zicbop
Fix broken testsuite like
"ERROR: gcc.target/riscv/cmo-zicbop-2.c   -Os : 1: too many arguments for " dg-do 1 compile target { { rv32-*-*}} "

gcc/testsuite/ChangeLog:

	* gcc.target/riscv/cmo-zicbop-1.c: Fix missing { before target .
	* gcc.target/riscv/cmo-zicbop-2.c: Likewise.
	* gcc.target/riscv/prefetch-zicbop.c:Likewise.
	* gcc.target/riscv/prefetch-zihintntl.c:Likewise.