libgcobol: Use strchr instead of index
valconf.cc doesn't compile on Solaris:

cobol/valconv.cc: In function ‘bool __gg__string_to_numeric_edited(char*, char*, int, int, const char*)’:
cobol/valconv.cc:856:40: error: ‘index’ was not declared in this scope; did you mean ‘Rindex’?
  856 |         const char *decimal_location = index(dest, __gg__decimal_point);      |                                        ^~~~~
     |                                        Rindex

On Solaris, it's only declared in <strings.h>.  While one could get that
included, it's way easier to just use strchr as is already the case in
other instances.

Bootstrapped without regressions on amd64-pc-solaris2.11,
sparcv9-sun-solaris2.11, and x86_64-pc-linux-gnu.

2025-04-08  Rainer Orth  <ro@CeBiTec.Uni-Bielefeld.DE>

	libgcobol:
	* valconv.cc (__gg__string_to_numeric_edited): Use strchr instead
	of index.