re PR other/50991 (crtstuff.c:65:23: fatal error: libgcc_tm.h: No such file or  directory)
	PR other/50991
	* Makefile.in: Make EXTRA_PARTS depend on libgcc_tm.h instead of
	extra-parts.

From-SVN: r181039