Fix sloppy test case.
This test case failed with

.../inline-mem-set-1.c:49:20: error: size of array 'p' exceeds maximum object size '32767'
.../inline-mem-set-1.c:54:22: error: size of array 'p' exceeds maximum object size '32767'

	PR testsuite/52641
gcc/testsuite/
	* gcc.dg/torture/inline-mem-set-1.c: Require size20plus.