c++: use nesting and counts in print_candidates
In r15-6116-gd3dd24acd74605 I updated print_z_candidates to print a
count of the number of candidates, and to show the number of each
candidate in the list if there is more than one.

The following patch updates print_candidates to work in a similar
way, showing counts, numbering, and using nesting.

Consider this test case for which we print 2 candidates:

class foo
{
public:
  void test (int i, int j, void *ptr, int k);
  void test (int i, int j, int k);
};

// Wrong "const"-ness of a param, for one of the overloads (param 3).
void foo::test (int i, int j, const void *ptr, int k)
{
}

The output before the patch is:

test.cc:9:6: error: no declaration matches ‘void foo::test(int, int, const void*, int)’
    9 | void foo::test (int i, int j, const void *ptr, int k)
      |      ^~~
test.cc:5:8: note: candidates are: ‘void foo::test(int, int, int)’
    5 |   void test (int i, int j, int k);
      |        ^~~~
test.cc:4:8: note:                 ‘void foo::test(int, int, void*, int)’
    4 |   void test (int i, int j, void *ptr, int k);
      |        ^~~~
test.cc:1:7: note: ‘class foo’ defined here
    1 | class foo
      |       ^~~

With the patch, the output looks like:

test.cc:9:6: error: no declaration matches ‘void foo::test(int, int, const void*, int)’
    9 | void foo::test (int i, int j, const void *ptr, int k)
      |      ^~~
  • there are 2 candidates
    • candidate 1: ‘void foo::test(int, int, int)’
      test.cc:5:8:
          5 |   void test (int i, int j, int k);
            |        ^~~~
    • candidate 2: ‘void foo::test(int, int, void*, int)’
      test.cc:4:8:
          4 |   void test (int i, int j, void *ptr, int k);
            |        ^~~~
test.cc:1:7: note: ‘class foo’ defined here
    1 | class foo
      |       ^~~

which I believe is much more readable.

I dabbled with removing the "there is 1 candidate" line for the case of
a single candidate, but I think I prefer it to be present.

FWIW I've been experimenting with followups that
* show more nested information about the problems (e.g. the "void *"
vs "const void *" mismatch) - having the candidates be nested is a
useful step towards that
* potentially look at the "edit distance" of the type signatures to find
close matches, and perhaps reordering/highlighting them (e.g. in the
above candidate 2 is arguably a closer match than candidate 1, due to
the "const" snafu) - gathering an auto_vec might help with that.

gcc/cp/ChangeLog:
	* call.cc (print_z_candidates): Move inform_n call into a new
	inform_num_candidates function.
	* class.cc (check_methods): Pass location to call to
	print_candidates.
	(resolve_address_of_overloaded_function): Likewise.
	* cp-tree.h (print_candidates): Add location_t param.
	(inform_num_candidates): New decl.
	* decl.cc (make_typename_type): Pass location to call to
	print_candidates.
	(reshape_init_class): Likewise.
	(lookup_and_check_tag): Likewise.
	* decl2.cc (check_classfn): Likewise.
	* error.cc (qualified_name_lookup_error): Likewise.
	* init.cc (build_new_1): Likewise.
	* name-lookup.cc (lookup_using_decl): Likewise.
	(set_decl_namespace): Likewise.
	(push_namespace): Likewise.
	* parser.cc (cp_parser_nested_name_specifier_opt): Likewise.
	(cp_parser_lookup_name): Likewise.
	* pt.cc  (print_candidates_1): Drop, converting the looping part
	into...
	(flatten_candidates): ...this new function.
	(inform_num_candidates): New function.
	(print_candidates): Use flatten_candidates to build an auto_vec
	of candidates, and use this to print them here, rather than in
	print_candidates_1.  Eliminate the dynamic allocation of spaces
	for a prefix in favor of printing "candidate %i" when there is
	more than one candidate.  Add "error_loc" param and pass it to
	inform_num_candidates to show a heading, and add nesting levels
	for it and for the candidate notes.
	(determine_specialization): Pass location to calls to
	print_candidates.
	* search.cc (lookup_member): Likewise.
	* semantics.cc (finish_id_expression_1): Likewise.

gcc/testsuite/ChangeLog:
	* g++.dg/cpp0x/inline-ns2.C: Make dg-message directives non-empty.
	* g++.dg/cpp23/explicit-obj-lambda11.C: Prune the extra note.
	* g++.dg/diagnostic/bad-fndef-1.C: New test.
	* g++.dg/lookup/decl1.C: Give the dg-message directives different
	messages.
	* g++.dg/lookup/using17.C: Update expected output.
	* g++.dg/parse/non-dependent2.C: Likewise.
	* g++.old-deja/g++.other/lineno2.C: Give the dg-message directives
	different messages.
	* g++.old-deja/g++.pt/t37.C: Likewise.

Signed-off-by: David Malcolm <dmalcolm@redhat.com>