Testsuite, i386: mark test as requiring dfp
Test currently fails on darwin with:
error: decimal floating-point not supported for this target

gcc/testsuite/ChangeLog:

	* gcc.target/i386/pr112445.c: Require dfp.