libstdc++: Avoid '-Wunused-parameter' for 'nofollow' in static member function 'static std::filesystem::__gnu_posix::DIR* std::filesystem::_Dir_base::openat(const _At_path&, bool)'
In a newlib configuration:

    In file included from ../../../../../source-gcc/libstdc++-v3/src/c++17/fs_dir.cc:37,
                     from ../../../../../source-gcc/libstdc++-v3/src/c++17/cow-fs_dir.cc:26:
    ../../../../../source-gcc/libstdc++-v3/src/c++17/../filesystem/dir-common.h: In static member function ‘static std::filesystem::__gnu_posix::DIR* std::filesystem::_Dir_base::openat(const _At_path&, bool)’:
    ../../../../../source-gcc/libstdc++-v3/src/c++17/../filesystem/dir-common.h:210:36: error: unused parameter ‘nofollow’ [-Werror=unused-parameter]
      210 |   openat(const _At_path& atp, bool nofollow)
          |                               ~~~~~^~~~~~~~

	libstdc++-v3/
	* src/filesystem/dir-common.h (openat): Tag 'nofollow' as
	'[[maybe_unused]]'.

(cherry picked from commit 5029c4bd330849fd6513b290d38bce853b320c5b)