testsuite: powerpc64: Fix gcc.dg/asm-hard-reg-5.c
Test gcc.dg/asm-hard-reg-5.c might fail on powerpc64 with:

gcc.dg/asm-hard-reg-5.c:27:3: error: register 5 for operand 0 isn't suitable for data type
gcc.dg/asm-hard-reg-5.c:34:3: error: register 5 for operand 0 isn't suitable for data type

For powerpc64le there exists no CPU without altivec support which is why
-maltivec is implied.  For powerpc64 this does not hold which is why for
this test -maltivec must be specified, or the other way around must be
skipped if there is no altivec support.

gcc/testsuite/ChangeLog:

	* gcc.dg/asm-hard-reg-5.c: Skip on powerpc64 in case of no
	altivec support.