i386: Fix up recent cpuinfo.h change for FEATURE_AVX10V2AUX
The r17-2973 change broke
+FAIL: gcc.target/i386/builtin_target.c (test for excess errors)
+UNRESOLVED: gcc.target/i386/builtin_target.c compilation failed to produce executable
Excess errors:
.../common/config/i386/cpuinfo.h:1127:7: error: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]

The following patch makes it valid C89 and cleans it up a little bit.

2026-08-06  Jakub Jelinek  <jakub@redhat.com>

	* common/config/i386/cpuinfo.h (get_available_features): Make
	last change valid C89.  Formatting fix.