d: Fix undefined reference to lambda defined in private enum [PR109108]
Previously lambdas were connected to the module they were defined in.
Now they are emitted into every referencing compilation unit, and are
given one-only linkage.

	PR d/109108

gcc/d/ChangeLog:

	* decl.cc (get_symbol_decl): Set DECL_LAMBDA_FUNCTION_P on function
	literals.
	(start_function): Unconditionally unset DECL_EXTERNAL.
	(set_linkage_for_decl): Give lambda functions one-only linkage.

gcc/testsuite/ChangeLog:

	* gdc.dg/torture/torture.exp (srcdir): New proc.
	* gdc.dg/torture/imports/pr109108.d: New test.
	* gdc.dg/torture/pr109108.d: New test.

(cherry picked from commit 423d34f61c43e400f0d5b837fe93c83963b2ecdd)