testsuite: Fix up pr113622-{2,3}.c for i686-linux [PR113622]
The 2 new tests FAIL for me on i686-linux:
.../gcc/testsuite/gcc.target/i386/pr113622-2.c:5:14: error: data type of 'a' isn't suitable for a register
.../gcc/testsuite/gcc.target/i386/pr113622-2.c:5:29: error: data type of 'b' isn't suitable for a register
.../gcc/testsuite/gcc.target/i386/pr113622-2.c:5:44: error: data type of 'c' isn't suitable for a register
The problem is that the tests use vectors of double, something added
only in SSE2, while the testcases ask for just -msse which only provides
vectors of floats.

So, either it should be using floats instead of doubles, or we need
to add -msse2 to dg-options.

I've done the latter.

2024-01-30  Jakub Jelinek  <jakub@redhat.com>

	PR middle-end/113622
	* gcc.target/i386/pr113622-2.c: Use -msse2 instead of -msse in
	dg-options.
	* gcc.target/i386/pr113622-3.c: Likewise.