Skip sloppy PR121035 test
gcc.dg/pr121035.c failed with

FAIL: gcc.dg/pr121035.c (test for excess errors)
Excess errors:
gcc.dg/pr121035.c:92:1: error: incompatible types in 'PHI' argument 1
unsigned int
long unsigned int
_11 = PHI <0(5), 4294967295(6)>
gcc.dg/pr121035.c:92:1: error: type mismatch in binary expression
unsigned int
unsigned int
long unsigned int
_6 = g_15 * 4294967294;

so the test case assumes int32plus at the least, changed accordingly.

gcc/testsuite/
	PR testsuite/121035
	* gcc.dg/pr121035.c: Require int32plus.