re PR tree-optimization/63915 (gomp/pr60823-2.c:31:1: error: dead STMT in EH table)
	PR tree-optimization/63915
	* tree-vect-stmts.c (vectorizable_simd_clone_call): Pass
	true instead of false as last argument to gsi_replace.

	* c-c++-common/gomp/pr60823-4.c: New test.

From-SVN: r217759