riscv: Fix compiler warning in thead.cc
A recent commit introduced a compiler warning in thead.cc:
error: invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]
 1144 |       fprintf (file, "(%s),"HOST_WIDE_INT_PRINT_DEC",%u", reg_names[REGNO (addr.reg)],
      |                      ^

This commit addresses this issue and breaks the line such that it won't
exceed 80 characters.

gcc/ChangeLog:

	* config/riscv/thead.cc (th_print_operand_address): Fix compiler
	warning.

Signed-off-by: Christoph Müllner <christoph.muellner@vrull.eu>