s390: Fix generation of s390-gen-builtins.h
By default the preprocessed output includes linemarkers.  This leads to
an error if -pedantic is used as e.g. during bootstrap:

s390-gen-builtins.h:1:3: error: style of line directive is a GCC extension [-Werror]

Fixed by omitting linemarkers while generating s390-gen-builtins.h.

gcc/ChangeLog:

	* config/s390/t-s390: Generate s390-gen-builtins.h without
	linemarkers.