testsuite: Fix another issue with sve-sizeless-[12].C
There is a different error message expected on line 165 (for both files).
It was expecting:
error: cannot convert 'svint16_t' to 'sveint8_t' in initialization
But now we get:
error: cannot convert 'svint16_t' to 'signed char' in initialization

This is because we support constructing scalable vectors rather than before.

So just update error message.

Pushed as obvious after a quick test for aarch64-linux-gnu.

gcc/testsuite/ChangeLog:

	* g++.dg/ext/sve-sizeless-1.C: Update error message for line 165.
	* g++.dg/ext/sve-sizeless-2.C: Likewise.

Signed-off-by: Andrew Pinski <quic_apinski@quicinc.com>