Use unique_ptr in more places in pretty_printer/diagnostics: 'gcc/config/gcn/mkoffload.cc' [PR116613]
After recent commit bf43fe6aa966eaf397ea3b8ebd6408d3d124e285
"Use unique_ptr in more places in pretty_printer/diagnostics [PR116613]":

    [...]
    In file included from ../../source-gcc/gcc/config/gcn/mkoffload.cc:31:0:
    ../../source-gcc/gcc/diagnostic.h:29:3: error: #error "You must define INCLUDE_MEMORY before including system.h to use diagnostic.h"
     # error "You must define INCLUDE_MEMORY before including system.h to use diagnostic.h"
       ^
    In file included from ../../source-gcc/gcc/diagnostic.h:34:0,
                     from ../../source-gcc/gcc/config/gcn/mkoffload.cc:31:
    ../../source-gcc/gcc/pretty-print.h:29:3: error: #error "You must define INCLUDE_MEMORY before including system.h to use pretty-print.h"
     # error "You must define INCLUDE_MEMORY before including system.h to use pretty-print.h"
       ^
    In file included from ../../source-gcc/gcc/diagnostic.h:34:0,
                     from ../../source-gcc/gcc/config/gcn/mkoffload.cc:31:
    ../../source-gcc/gcc/pretty-print.h:280:16: error: 'unique_ptr' in namespace 'std' does not name a template type
       virtual std::unique_ptr<pretty_printer> clone () const;
                    ^
    In file included from ../../source-gcc/gcc/config/gcn/mkoffload.cc:31:0:
    ../../source-gcc/gcc/diagnostic.h:585:32: error: 'std::unique_ptr' has not been declared
       void set_output_format (std::unique_ptr<diagnostic_output_format> output_format);
                                    ^
    [...]

	PR other/116613
	gcc/
	* config/gcn/mkoffload.cc: Add '#define INCLUDE_MEMORY'.