testsuite: Fix g++.dg/DRs/dr2581-1.C etc. on non-Linux
The g++.dg/DRs/dr2581-?.C tests FAIL on several targets in two ways:

* Both tests FAIL on a couple of targets in the same way:

FAIL: g++.dg/DRs/dr2581-1.C  -std=c++11  (test for warnings, line 25)
FAIL: g++.dg/DRs/dr2581-1.C  -std=c++17  (test for warnings, line 25)
FAIL: g++.dg/DRs/dr2581-1.C  -std=c++20  (test for warnings, line 25)
FAIL: g++.dg/DRs/dr2581-1.C  -std=c++23  (test for warnings, line 25)
FAIL: g++.dg/DRs/dr2581-1.C  -std=c++26  (test for warnings, line 25)
FAIL: g++.dg/DRs/dr2581-2.C  -std=c++11  (test for errors, line 25)
FAIL: g++.dg/DRs/dr2581-2.C  -std=c++14  (test for errors, line 25)
FAIL: g++.dg/DRs/dr2581-2.C  -std=c++17  (test for errors, line 25)
FAIL: g++.dg/DRs/dr2581-2.C  -std=c++20  (test for errors, line 25)
FAIL: g++.dg/DRs/dr2581-2.C  -std=c++23  (test for errors, line 25)
FAIL: g++.dg/DRs/dr2581-2.C  -std=c++26  (test for errors, line 25)

  i.e. the __STDC_ISO_10646__ warning is missing.  This happens on
  Solaris, FreeBSD, Darwin, and several embedded targets.  While
  __STDC_ISO_10646__ already exists in C99, it's optional there and
  seems to be only defined on Linux/glibc.  Thus this patch xfail's this
  check on non-Linux.

* Besides, on Solaris only there are more failures for -std=c++11 to
  c++26, like

FAIL: g++.dg/DRs/dr2581-2.C  -std=c++11  (test for warnings, line 24)
FAIL: g++.dg/DRs/dr2581-2.C  -std=c++11 (test for excess errors)

Excess errors:
g++.dg/DRs/dr2581-2.C:24:9: error: '__STDC_VERSION__' redefined

  This happens because g++ always predefines __STDC_VERSION__ on
  Solaris, so this patch expects an error instead of a warning here.

Tested on i386-pc-solaris2.11, sparc-sun-solaris2.11,
x86_64-apple-darwin25.1.0, and x86_64-pc-linux-gnu.

2025-11-20  Rainer Orth  <ro@CeBiTec.Uni-Bielefeld.DE>

	gcc/testsuite:
	* g++.dg/DRs/dr2581-1.C (__STDC_ISO_10646__): xfail on non-Linux.
	* g++.dg/DRs/dr2581-2.C: Likewise.
	(__STDC_VERSION__): Expect error instead of warning on Solaris.