re PR libstdc++/85768 (FreeBSD bootstrap fails due to undefined reference to 'backtrace')
2018-05-25  François Dumont  <fdumont@gcc.gnu.org>

	PR libstdc++/85768
	* src/c++11/debug.cc: Remove backtrace usage.

From-SVN: r260761