RISC-V: Fix detection of zifencei support for binutils
- binutils will complain version info is not found if default ISA spec
  is 2.2 for binutils.

Error: cannot find default versions of the ISA extension `zifencei'

gcc/ChangeLog:

	* configure.ac: Fix detection for zifencei support.
	* configure: Regenerate.

(cherry picked from commit affdeda16ef7fbd34f850443fe63bb407714297e)