Placate GCC 4.8
    In file included from [...]/gcc/rust/parse/rust-parse.h:645:0,
                     from [...]/gcc/rust/rust-session-manager.cc:34:
    [...]/gcc/rust/parse/rust-parse-impl.h: In instantiation of 'std::unique_ptr<Rust::AST::AttrInput> Rust::Parser<ManagedTokenSource>::parse_attr_input() [with ManagedTokenSource = Rust::Lexer]':
    [...]/gcc/rust/parse/rust-parse-impl.h:522:66:   required from 'Rust::AST::Attribute Rust::Parser<ManagedTokenSource>::parse_attribute_body() [with ManagedTokenSource = Rust::Lexer]'
    [...]/gcc/rust/parse/rust-parse-impl.h:493:59:   required from 'Rust::AST::Attribute Rust::Parser<ManagedTokenSource>::parse_inner_attribute() [with ManagedTokenSource = Rust::Lexer]'
    [...]/gcc/rust/parse/rust-parse-impl.h:444:58:   required from 'std::vector<Rust::AST::Attribute> Rust::Parser<ManagedTokenSource>::parse_inner_attributes() [with ManagedTokenSource = Rust::Lexer]'
    [...]/gcc/rust/parse/rust-parse-impl.h:402:69:   required from 'Rust::AST::Crate Rust::Parser<ManagedTokenSource>::parse_crate() [with ManagedTokenSource = Rust::Lexer]'
    [...]/gcc/rust/rust-session-manager.cc:458:43:   required from here
    [...]/gcc/rust/parse/rust-parse-impl.h:734:9: error: could not convert 'input_tree' from 'std::unique_ptr<Rust::AST::DelimTokenTree>' to 'std::unique_ptr<Rust::AST::AttrInput>'
      return input_tree;
             ^
    [...]/gcc/rust/parse/rust-parse-impl.h:792:9: error: could not convert 'attr_input_lit' from 'std::unique_ptr<Rust::AST::AttrInputLiteral>' to 'std::unique_ptr<Rust::AST::AttrInput>'
      return attr_input_lit;
             ^

    In file included from [...]/gcc/rust/parse/rust-parse.h:645:0,
                     from [...]/gcc/rust/rust-session-manager.cc:34:
    [...]/gcc/rust/parse/rust-parse-impl.h: In instantiation of 'std::unique_ptr<Rust::AST::TraitItem> Rust::Parser<ManagedTokenSource>::parse_trait_item() [with ManagedTokenSource = Rust::Lexer]':
    [...]/gcc/rust/parse/rust-parse-impl.h:4693:70:   required from 'std::unique_ptr<Rust::AST::Trait> Rust::Parser<ManagedTokenSource>::parse_trait(Rust::AST::Visibility, std::vector<Rust::AST::Attribute>) [with ManagedTokenSource = Rust::Lexer]'
    [...]/gcc/rust/parse/rust-parse-impl.h:1268:67:   required from 'std::unique_ptr<Rust::AST::VisItem> Rust::Parser<ManagedTokenSource>::parse_vis_item(std::vector<Rust::AST::Attribute>) [with ManagedTokenSource = Rust::Lexer]'
    [...]/gcc/rust/parse/rust-parse-impl.h:1048:53:   required from 'std::unique_ptr<Rust::AST::Item> Rust::Parser<ManagedTokenSource>::parse_item(bool) [with ManagedTokenSource = Rust::Lexer]'
    [...]/gcc/rust/parse/rust-parse-impl.h:410:58:   required from 'Rust::AST::Crate Rust::Parser<ManagedTokenSource>::parse_crate() [with ManagedTokenSource = Rust::Lexer]'
    [...]/gcc/rust/rust-session-manager.cc:458:43:   required from here
    [...]/gcc/rust/parse/rust-parse-impl.h:4876:13: error: could not convert 'macro_invoc' from 'std::unique_ptr<Rust::AST::MacroInvocationSemi>' to 'std::unique_ptr<Rust::AST::TraitItem>'
          return macro_invoc;
                 ^