re PR middle-end/52592 (compilation failure with undefined reference to `__builtin_iround')
	PR middle-end/52592
	* builtins.c (expand_builtin_int_roundingfn_2): If expanding
	BUILT_IN_IR{INT,OUND}* using optab fails, emit lr{int,ound}*
	calls instead of __builtin_ir{int,ound}*.

	* gcc.dg/pr52592.c: New test.

Co-Authored-By: Andrew Pinski <apinski@cavium.com>

From-SVN: r185432