Fix sloppy PR93231 test.
This test failed with

gcc.dg/pr93231.c:12:48: warning: right shift count >= width of type [-Wshift-count-overflow]
gcc.dg/pr93231.c:30:5: error: array of inappropriate type initialized from string constant

As it's unclear how to make it work on int16, require int32plus.

gcc/testsuite/
	PR testsuite/93231
	* gcc.dg/pr93231.c: Require int32plus.