c++: UX improvements for close matches in print_candidates
This patch improves the UX for various cases of "no declaration matches"
where print_candidates encounters a close match.

For example, consider the const vs non-const here:

class foo
{
public:
  void test (int i, int j, void *ptr, int k);
};

// Wrong "const"-ness of param 3.
void foo::test (int i, int j, const void *ptr, int k)
{
}

where we emit (with indentation provided by the prior patch):

test.cc:8:6: error: no declaration matches ‘void foo::test(int, int, const void*, int)’
    8 | void foo::test (int i, int j, const void *ptr, int k)
      |      ^~~
  • there is 1 candidate
    • candidate is: ‘void foo::test(int, int, void*, int)’
      test.cc:4:8:
          4 |   void test (int i, int j, void *ptr, int k);
            |        ^~~~
test.cc:1:7: note: ‘class foo’ defined here
    1 | class foo
      |       ^~~

which requires the user to look through the pairs of parameters
and try to find the mismatch by eye.

This patch adds notes identifying that parameter 3 has the mismatch, and
what the mismatch is, using a pair of colors to highlight and contrast
the type mismatch.

test.cc:8:6: error: no declaration matches ‘void foo::test(int, int, const void*, int)’
    8 | void foo::test (int i, int j, const void *ptr, int k)
      |      ^~~
  • there is 1 candidate
    • candidate is: ‘void foo::test(int, int, void*, int)’
      test.cc:4:8:
          4 |   void test (int i, int j, void *ptr, int k);
            |        ^~~~
      • parameter 3 of candidate has type ‘void*’...
        test.cc:4:34:
            4 |   void test (int i, int j, void *ptr, int k);
              |                            ~~~~~~^~~
      • ...which does not match type ‘const void*’
        test.cc:8:43:
            8 | void foo::test (int i, int j, const void *ptr, int k)
              |                               ~~~~~~~~~~~~^~~
test.cc:1:7: note: ‘class foo’ defined here
    1 | class foo
      |       ^~~

This also works for the "this" case, improving the UX for messing up
const vs non-const between decls and defns of member functions; see
bad-fndef-2.C for an example.

For screenshots showing the colorization effect, see slides 9-12 of my
Cauldron talk:
https://gcc.gnu.org/wiki/cauldron2025#What.27s_new_with_diagnostics_in_GCC_16
("Hierarchical diagnostics (not yet in trunk)").

gcc/cp/ChangeLog:
	* call.cc (get_fndecl_argument_location): Use DECL_SOURCE_LOCATION
	for "this".
	* cp-tree.h (class candidate_context): New.
	(print_candidates): Add optional candidate_context param.
	* decl2.cc: Include "gcc-rich-location.h" and
	"tree-pretty-print-markup.h".
	(struct fndecl_signature): New.
	(class parm_rich_location): New.
	(class fndecl_comparison): New.
	(class decl_mismatch_context): New.
	(check_classfn): For the "no declaration matches" case, pass an
	instance of a custom candidate_context subclass to
	print_candidates, using fndecl_comparison to report on close
	matches.
	* pt.cc (print_candidates): Add optional candidate_context param.
	Use it if provided to potentially emit per-candidate notes.

gcc/testsuite/ChangeLog:
	* g++.dg/diagnostic/bad-fndef-1.C: Add directives to expect
	"void *" vs "const void *" notes about parameter 3 of the close
	candidate.
	* g++.dg/diagnostic/bad-fndef-2.C: New test.
	* g++.dg/diagnostic/bad-fndef-3.C: New test.
	* g++.dg/diagnostic/bad-fndef-4.C: New test.
	* g++.dg/diagnostic/bad-fndef-5.C: New test.
	* g++.dg/diagnostic/bad-fndef-6.C: New test.
	* g++.dg/diagnostic/bad-fndef-7.C: New test.
	* g++.dg/diagnostic/bad-fndef-7b.C: New test.
	* g++.dg/diagnostic/bad-fndef-8.C: New test.
	* g++.dg/diagnostic/bad-fndef-9.C: New test.

Signed-off-by: David Malcolm <dmalcolm@redhat.com>