Address 'error: ‘*<unknown>.Rust::HIR::ArrayType::<anonymous>.Rust::HIR::TypeNoBounds::<anonymous>.Rust::HIR::Type::mappings’ is used uninitialized [-Werror=uninitialized]' diagnostic [#336]
... by doing the same as in the "assignment operator to deep copy pointers" a
few lines later.  I have not verified what's (supposed to be) going on here;
that code seems unused, and thus untested, and thus I marked it up as such.

    In file included from [...]/gcc/rust/hir/tree/rust-hir-full.h:29,
                     from [...]/gcc/rust/backend/rust-compile.h:23,
                     from [...]/gcc/rust/backend/rust-compile.cc:19:
    [...]/gcc/rust/hir/tree/rust-hir-type.h: In copy constructor ‘Rust::HIR::ArrayType::ArrayType(const Rust::HIR::ArrayType&)’:
    [...]/gcc/rust/hir/tree/rust-hir-type.h:607:21: error: ‘*<unknown>.Rust::HIR::ArrayType::<anonymous>.Rust::HIR::TypeNoBounds::<anonymous>.Rust::HIR::Type::mappings’ is used uninitialized [-Werror=uninitialized]
      607 |     : TypeNoBounds (mappings), elem_type (other.elem_type->clone_type ()),
          |                     ^~~~~~~~