s390: Fix builtin s390_vec_load_bndry for C++
The second argument for builtin s390_vec_load_bndry must be an integer
constant.  The C++ front end wraps a constant inside a NON_LVALUE_EXPR
which we need to unpack first.  Otherwise we bail out in
s390_adjust_builtin_arglist():

t.C: In function ‘__vector(4) unsigned int test(const unsigned int*)’:
t.C:7:42: error: constant value required for builtin ‘__vector(16) signed char __builtin_s390_vlbb(const void*, int)’ argument 2
    7 |     return __builtin_s390_vec_load_bndry (x, 4096);
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~

gcc/ChangeLog:

	* config/s390/s390-c.cc (s390_adjust_builtin_arglist): Fix
	builtin s390_vec_load_bndry for C++.