Resolve 'error: unused parameter' in 'gcc/cp/decl2.cc:one_static_initialization_or_destruction'
    [...]/gcc/cp/decl2.cc: In function ‘void one_static_initialization_or_destruction(tree, tree, bool, bool)’:
    [...]/gcc/cp/decl2.cc:4171:48: error: unused parameter ‘omp_target’ [-Werror=unused-parameter]
     4171 |                                           bool omp_target)
          |                                           ~~~~~^~~~~~~~~~
    cc1plus: all warnings being treated as errors
    make[3]: *** [cp/decl2.o] Error 1

Fix-up for og12 commit abcb5dbac666513c798e574808f849f76a1c0799
"[og12] OpenMP: Constructors and destructors for "declare target" static aggregates".

	gcc/cp/
	* decl2.cc (one_static_initialization_or_destruction): Remove
	'omp_target' formal parameter.  Adjust all users.