re PR go/52084 (go tests fail to link on powerpc-linux-gnu (undefined reference to __sync_add_and_fetch_8))
	PR go/52084
libgo: Provide more __sync functions if required.

From-SVN: r184138