Fortran: Add code gen for do,concurrent's LOCAL/LOCAL_INIT: Fix 'static_assert' [PR101602]
Fix-up for commit 2d7e1d6e40a13a5f160b584336795b80f193ec3b
"Fortran: Add code gen for do,concurrent's LOCAL/LOCAL_INIT [PR101602]":

    ../../source-gcc/gcc/fortran/trans-stmt.cc: In function ‘void gfc_trans_concurrent_locality_spec(bool, stmtblock_t*, std::vector<symbol_and_tree_t>*, gfc_expr_list**)’:
    ../../source-gcc/gcc/fortran/trans-stmt.cc:5157:59: error: expected ‘,’ before ‘)’ token
       static_assert (LOCALITY_LOCAL_INIT - LOCALITY_LOCAL == 1);
                                                               ^
    ../../source-gcc/gcc/fortran/trans-stmt.cc:5157:59: error: expected string-literal before ‘)’ token
    make[2]: *** [Makefile:1210: fortran/trans-stmt.o] Error 1

	PR fortran/101602
	gcc/fortran/
	* trans-stmt.cc (gfc_trans_concurrent_locality_spec): Fix
	'static_assert'.