jit: fix for write_reproducer [PR117886]
The original generated .c reproducer for PR jit/117886 did not compile,
with:

main.c: In function ‘create_code’:
main.c:600:9: error: initialization of ‘gcc_jit_rvalue *’ from incompatible pointer type ‘gcc_jit_lvalue *’ [-Wincompatible-pointer-types]
  600 |         local__1,
      |         ^~~~~~~~

The issue is that recording::ctor::write_reproducer was missing
creation of casts to gcc_jit_rvalue * for
gcc_jit_context_new_array_constructor and
gcc_jit_context_new_struct_constructor.

Fixed thusly.

gcc/jit/ChangeLog:
	PR jit/117886
	* jit-recording.cc (reproducer::get_identifier_as_rvalue): Handle
	null memento.
	(reproducer::get_identifier_as_lvalue): Likewise.
	(reproducer::get_identifier_as_type): Likewise.
	(recording::ctor::write_reproducer): Use get_identifier_as_rvalue
	rather than get_identifier when writing out gcc_jit_rvalue *
	expressions.

gcc/testsuite/ChangeLog:
	PR jit/117886
	* jit.dg/all-non-failing-tests.h: Add
	test-pr117886-write-reproducer.c.
	* jit.dg/test-pr117886-write-reproducer.c: New test.

Signed-off-by: David Malcolm <dmalcolm@redhat.com>