Un-break nvptx libgomp build
    In file included from [...]/libgomp/config/nvptx/allocator.c:49:
    [...]/libgomp/config/nvptx/../../basic-allocator.c:52:2: error: invalid preprocessing directive #deine; did you mean #define?
       52 | #deine BASIC_ALLOC_YIELD
          |  ^~~~~
          |  define

Yes, indeed.

Fix-up for og12 commit 9583738a62a33a276b2aad980a27e77097f95924
"nvptx, libgomp: Move the low-latency allocator code".

	libgomp/
	* basic-allocator.c (BASIC_ALLOC_YIELD): instead of '#deine',
	'#define' it.