aarch64: Fix condition accepted by mov<ALLI>cc
Reject QI/HImode conditions, which would require extension in
order to compare.  Fixes

z.c:10:1: error: unrecognizable insn:
   10 | }
      | ^
(insn 23 22 24 2 (set (reg:CC 66 cc)
        (compare:CC (reg:HI 128)
            (reg:HI 127))) "z.c":6:6 -1
     (nil))
during RTL pass: vregs

gcc:
	* config/aarch64/aarch64.md (mov<ALLI>cc): Accept MODE_CC
	conditions directly; reject QI/HImode conditions.

gcc/testsuite:
	* gcc.target/aarch64/cmpbr-3.c: New.
	* gcc.target/aarch64/ifcvt_multiple_sets_rewire.c: Simplify
	test for csel by ignoring the actual registers used.