c++: fix return type of __cxa_bad_array_new_length
We were lying about the return type, but that's not necessary; we already
need to handle a COND_EXPR where one side is void for THROW_EXPR.

This fixes an execution failure on nvptx:
error: Prototype doesn't match for '__cxa_throw_bad_array_new_length'

gcc/cp/ChangeLog:

	* init.cc (throw_bad_array_new_length): Returns void.

(cherry picked from commit cb537f0d838bac376bfe5e6d765e19cd3af01031)