re PR target/46040 (crtstuff.c:308:26: error: '__DTOR_LIST__' undeclared)
gcc/
	PR target/46040
	* config.gcc (arm*-*-linux-*eabi): Use bpabi-lib.h.
	(arm*-*-uclinux*eabi, arm*-*-eabi*): Likewise.

libgcc/
	PR target/46040
	* config/arm/bpabi.h: Rename to...
	* config/arm/bpabi-lib.h: ...this.

From-SVN: r167751