Skip sloppy gcc.dg/tree-ssa/pr121264.c
This test case faied with

FAIL: gcc.dg/tree-ssa/pr121264.c (test for excess errors)
Excess errors:
.../gcc.dg/tree-ssa/pr121264.c:6:25: error: size of array 'c' is too large

since it's assuming size32plus obviously, hence require size32plus
so it skips when size_t is smaller than 32 bits.

gcc/testsuite/
	PR testsuite/121264
	* gcc.dg/tree-ssa/pr121264.c: Require size32plus.