pair-fusion: fix for older GCC
Older GCCs fail with:

  .../gcc/pair-fusion.cc: In member function ‘bool pair_fusion_bb_info::fuse_pair(bool, unsigned int, int, rtl_ssa::insn_info*, rtl_ssa::in
  sn_info*, base_cand&, const rtl_ssa::insn_range_info&)’:
  .../gcc/pair-fusion.cc:1790:40: error: ‘writeback’ is not a class, namespace, or enumeration
     if (m_pass->should_handle_writeback (writeback::ALL)

Renaming the enum type works around the name conflict with the local
variable and also prevents future similar conflicts.

gcc/ChangeLog:

	* pair-fusion.h (enum class writeback): Rename to...
	(enum class writeback_type): ...this.
	(struct pair_fusion): Adjust type name after renaming.
	* pair-fusion.cc (pair_fusion_bb_info::track_access): Likewise.
	(pair_fusion_bb_info::fuse_pair): Likewise.
	(pair_fusion::process_block): Likewise.