RISC-V: Refine the error msg for RVV intrinisc required ext
The RVV intrinisc API has sorts of required extension from both
the march or target attribute.  It will have error message similar
to below:

built-in function '__riscv_vsetvl_e8m4\(vl\)' requires the V ISA extension

However, it is not accurate as we have many additional sub extenstion
besides v extension.  For example, zvbb, zvbk, zvbc ... etc.  This patch
would like to refine the error message with a friendly hint for the
required extension.  For example as below:

vuint64m1_t
__attribute__((target("arch=+v")))
test_1 (vuint64m1_t op_1, vuint64m1_t op_2, size_t vl)
{
  return __riscv_vclmul_vv_u64m1 (op_1, op_2, vl);
}

When compile with march=rv64gc and target arch=+v, we will have error
message as below:

error: built-in function '__riscv_vclmul_vv_u64m1(op_1,  op_2,  vl)'
  requires the 'zvbc' ISA extension

Then the end-user will get the point that the *zvbc* extension is missing
for the intrinisc API easily.

The below tests are passed for this patch.
* The riscv fully regression tests.

gcc/ChangeLog:

	* config/riscv/riscv-vector-builtins-shapes.cc (build_one): Pass
	required_ext arg when invoke add function.
	(build_th_loadstore): Ditto.
	(struct vcreate_def): Ditto.
	(struct read_vl_def): Ditto.
	(struct vlenb_def): Ditto.
	* config/riscv/riscv-vector-builtins.cc (function_builder::add_function):
	Introduce new arg required_ext to fill in the register func.
	(function_builder::add_unique_function): Ditto.
	(function_builder::add_overloaded_function): Ditto.
	(expand_builtin): Leverage required_extensions_specified to
	check if the required extension is provided.
	* config/riscv/riscv-vector-builtins.h (reqired_ext_to_isa_name): New
	func impl to convert the required_ext enum to the extension name.
	(required_extensions_specified): New func impl to predicate if
	the required extension is well feeded.

gcc/testsuite/ChangeLog:

	* gcc.target/riscv/rvv/base/target_attribute_v_with_intrinsic-7.c: Adjust
	the error message for v extension.
	* gcc.target/riscv/rvv/base/target_attribute_v_with_intrinsic-8.c: Ditto.
	* gcc.target/riscv/rvv/base/intrinsic_required_ext-1.c: New test.
	* gcc.target/riscv/rvv/base/intrinsic_required_ext-10.c: New test.
	* gcc.target/riscv/rvv/base/intrinsic_required_ext-2.c: New test.
	* gcc.target/riscv/rvv/base/intrinsic_required_ext-3.c: New test.
	* gcc.target/riscv/rvv/base/intrinsic_required_ext-4.c: New test.
	* gcc.target/riscv/rvv/base/intrinsic_required_ext-5.c: New test.
	* gcc.target/riscv/rvv/base/intrinsic_required_ext-6.c: New test.
	* gcc.target/riscv/rvv/base/intrinsic_required_ext-7.c: New test.
	* gcc.target/riscv/rvv/base/intrinsic_required_ext-8.c: New test.
	* gcc.target/riscv/rvv/base/intrinsic_required_ext-9.c: New test.

Signed-off-by: Pan Li <pan2.li@intel.com>