Fix riscv build, no longer works with python2
Building riscv no longer works with python2:

> python ./config/riscv/arch-canonicalize -misa-spec=20191213 rv64gc
  File "./config/riscv/arch-canonicalize", line 229
    print(f"ERROR: Unhandled conditional dependency: '{ext_name}' with condition:", file=sys.stderr)
                                                                                 ^
SyntaxError: invalid syntax

On systems that have python aliased to python2 we chose that, even
when python3 is available.  Don't.

	* config.gcc (riscv*-*-*): Look for python3, then fall back
	to python.  Never use python2.