a68: Fix algol68 build on i686-linux
GCC with enabled algol68 fails to build on i686-linux, the error is
../../gcc/algol68/a68-low-multiples.cc:636:31: error: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘size_t’ {aka ‘unsigned int’} [-Werror=format=]
xasprintf is printf family, so it can't use %zd portably, so the
following patch uses what is used elsewhere, the HOST_SIZE_T_PRINT*
macros with (fmt_size_t) cast - the macros pick the smallest of
%d, %ld and %lld depending on SIZE_MAX, but it could still disagree
on the exact type and cause warnings or for hosts with say 24-bit
size_t it could be even larger, so the cast is needed to handle that.

2025-12-01  Jakub Jelinek  <jakub@redhat.com>

	* algol68/a68-low-multiples.cc (copy_multiple_dimension_elems): Use
	HOST_SIZE_T_PRINT_DEC in xasprintf format string and cast to
	fmt_size_t.