re PR middle-end/38652 (dse.c: In function get_call_args: dse.c:2309: error: target undeclared)
	PR middle-end/38652
	* dse.c: Include target.h.
	* Makefile.in (dse.o): Depend on $(TARGET_H).

From-SVN: r142949