cobol: Avoid conflict with timespec_t in system headers [PR119217]
util.cc doesn't compile on Solaris:

/vol/gcc/src/hg/master/local/gcc/cobol/util.cc:2135:7: error: using typedef-name ‘timespec_t’ after ‘class’
 2135 | class timespec_t {
      |       ^~~~~~~~~~

This happens because <time.h> declares timespec_t itself.  In fact,
POSIX.1 reserves every *_t identifier, so this is benign.

To avoid the problem, this patch renames the cobol timespec_t to
cbl_timespec.

Bootstrapped without regressions on amd64-pc-solaris2.11,
sparcv9-sun-solaris2.11, and x86_64-pc-linux-gnu.

2025-04-08  Rainer Orth  <ro@CeBiTec.Uni-Bielefeld.DE>

	gcc/cobol:
	PR cobol/119217
	* util.cc (class timespec_t): Rename to cbl_timespec.