OpenMP: Improve C/C++ parsing error message [PR109999]
Replace
  error: expected '#pragma omp' clause before ...
by the the more readable/clearer
  error: expected an OpenMP clause before ...

(And likewise for '#pragma acc' and OpenACC.)

	PR c/109999

gcc/c/ChangeLog:

	* c-parser.cc (c_parser_oacc_all_clauses,
	c_parser_omp_all_clauses): Improve error wording.

gcc/cp/ChangeLog:

	* parser.cc (cp_parser_oacc_all_clauses,
	cp_parser_omp_all_clauses): Improve error wording.

gcc/testsuite/ChangeLog:

	* c-c++-common/goacc/asyncwait-1.c: Update dg-error.
	* c-c++-common/goacc/clauses-fail.c: Likewise.
	* c-c++-common/goacc/data-2.c: Likewise.
	* c-c++-common/gomp/declare-target-2.c: Likewise.
	* c-c++-common/gomp/directive-1.c: Likewise.
	* c-c++-common/gomp/loop-transforms/tile-1.c: Likewise.
	* c-c++-common/gomp/loop-transforms/tile-2.c: Likewise.
	* c-c++-common/gomp/loop-transforms/unroll-2.c: Likewise.
	* g++.dg/goacc/data-1.C: Likewise.

(cherry picked from commit a899401404186843f38462c8fc9de733f19ce864)
(However, the tile-1.c, tile-2.c, and unroll-2.c change is only here.)