build: Add stdatomic.h to USER_H on OpenBSD
Otherwise libatomic build fails with:
../../../gcc/libatomic/fence.c:27:10: fatal error: stdatomic.h: No such file or directory
   27 | #include <stdatomic.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
../../../gcc/libatomic/flag.c:27:10: fatal error: stdatomic.h: No such file or directory
   27 | #include <stdatomic.h>

gcc/ChangeLog:

	* config/t-openbsd (USER_H): Add $(srcdir)/ginclude/stdatomic.h.

Signed-off-by: Pietro Monteiro <pietro@sociotechnical.xyz>
(cherry picked from commit d32c1f0238f33b0f6a3ef1b5b228678a92585094)