Cast return of strtol to unsigned int
strtol returns long, which is compared against unsigned int.  On 32-bit
hosts, it leads to

gcc/gentarget-def.c: In function void def_target_insn(const char*, const char*):
gcc/gentarget-def.c:88:34: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

This patch casts return of strtol to unsigned int to avoid the error.

	* gentarget-def.c (def_target_insn): Cast return of strtol to
	unsigned int.


git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@224993 138bc75d-0d04-0410-961f-82ee72b054a4