c++: Add missing explanations for is_constructible<Abstract>
Checking whether an abstract class type is constructible currently is
missing an explanation.  With this patch, we now get the following
output for an abstract type:

test.cpp:7:20: error: static assertion failed
    7 | static_assert(std::is_default_constructible_v<A>);
      |               ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  • ‘A’ is not default constructible, because
  • error: cannot construct an object of abstract type ‘A’
  • because the following virtual functions are pure within ‘A’:
    test.cpp:3:8:
        3 | struct A {
          |        ^
    • ‘virtual void A::foo()’
      test.cpp:4:18:
          4 |     virtual void foo() = 0;
            |                  ^~~

Before this patch, the diagnostic stopped after the "A is not default
constructible, because" message.

gcc/cp/ChangeLog:

	* method.cc (constructible_expr): Emit diagnostics for abstract
	types.
	* typeck2.cc (abstract_virtuals_error): Use more accurate
	wording for default case, and remove extranneous whitespace
	in favour of a nesting level.

gcc/testsuite/ChangeLog:

	* g++.dg/ext/is_constructible9.C: Add to testcase.

Signed-off-by: Nathaniel Shead <nathanieloshead@gmail.com>
Reviewed-by: Jason Merrill <jason@redhat.com>